### ISSUE TITLE
remove connected client information

### ISSUE THREAD

**Issue by Nachtpfoetchen** [freifunk-ffm/meshviewer#4]
At the moment the map shows the number of connected clients and way they are connected. Less metadata in the map is more good - like for privacy reasons for example. Some other freifunk mesh maps do not disclose how many devices are connected atm.

## Describe the solution you'd like
Deactivation of the clientnumber and connection type (2.4 GHz,5GHz and other) in the meshviewer

because less data is more good.

**Comment by MyIgel** [comment]
but has the downside that the (readily available) information is not shown which makes debugging / problem finding a pain (and can be accessed when querying nodes anyway)

**Comment by MyIgel** [comment]
Imho that should be implemented on the node level if needed, not on a map that only shows available information
